name:                formal-fsm-gui
version:             0.1.0.0
github:              "githubuser/formal-fsm-gui"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/formal-fsm-gui#readme>

dependencies:
- regex-tdfa
- base >= 4.7 && < 5
- aeson
- bytestring
- string-interpolate
- neat-interpolation
- containers
- text
- directory
- scotty
- wai
- wai-extra
- wai-middleware-static
- http-types
- base64-bytestring
- http-client
- http-client-tls
- http-types
- wai-cors
- process
- filepath
- ansi-terminal
- haskeline
- regex-posix
- split
- mtl
- transformers
- cmdargs
- time >= 1.11.1.1
- MissingH
- scheduler
- lens
- random
- yaml

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  formal-fsm-gui:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - formal-fsm-gui

tests:
  fsm:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - formal-fsm-gui
